#!/bin/bash

# this program is to copy data from EC2 instance to S3
# bucket

if [[ $# -lt 2 ]]; then
	echo "
	Usage: $0 <s3-bucket> <source1> [<source2> ...]

	destination: destination files or folders in S3 bucket
	source: source files or folder

	This program copy files from EC2 source to S3 bucket.
	"

	exit 1;
fi


# if a folder is given, a bit modification
if [[ -d "$1" ]]; then
	src="$1/*"
else
	src="$1"
fi

#echo $src; exit 1;

bucket="s3://$1/"
shift;

for src in "$@";
do
	# echo copying $src
	if [[ -d "$src" ]]; then
		src="$src/*"
	fi

	for f in `ls "$src"`
	do
		echo " --- $f "
		aws s3 cp $f $bucket
	done
done

