#!/bin/bash

function usage ()
{
	echo "
	Usage: $0 [-u or -i] <instance-id> [<format: text, table, or json>]

	The option -u and -i is to control what IP/hostname to return: 
	public or private, respectively. Default is public;
	";
	exit 1;
}

if [[ $# -lt 1 ]]; then
	usage;
fi

while getopts ":ui" opt; do
	case $opt in
		u)
			type='Public'
			;;
		i)
			type='Private'
			;;
		\?)
			usage
			;;
	esac
done

shift $((OPTIND -1))

if [[ -z $type ]]; then
	type='Public'
fi

instId=$1
fmt=${2:-table}

elements=${type}IpAddress,${type}DnsName

aws ec2 describe-instances --instance-ids $instId --output $fmt \
--query "Reservations[*].Instances[*].[$elements]"
#--query 'Reservations[*].Instances[*].[PublicIpAddress,PublicDnsName]'

