#!/bin/bash

fmt=${1:-table}

aws ec2 describe-instances --output $fmt --filters \
"Name=key-name,Values=[zhang-ssh,zzhang]" --query \
'Reservations[*].Instances[*].{ID:InstanceId,Type:InstanceType,Start:LaunchTime,State:State.Name}'
#'Reservations[*].Instances[*].[InstanceId,InstanceType,LaunchTime,State.Name]'

